{% set name = "citrination-client" %}
{% set version = "6.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bf59ad9ea1a771f2378f10d21c00a6ae09d9c62153fa351f73408dc5b86d2ae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - requests
    - requests-mock
    - six
    - pyyaml
    - pypif
    - setuptools

test:
  imports:
    - citrination_client

about:
  home: http://github.com/CitrineInformatics/python-citrination-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Reference implementation in python for Citrination api

  description: |
    Python client for accessing the Citrination api
  doc_url: http://citrineinformatics.github.io/python-citrination-client/
  dev_url: https://github.com/CitrineInformatics/python-citrination-client

extra:
  recipe-maintainers:
    - eddotman
    - maxhutch
    - sparadiso
    - jsomara
    - sdedkins
