{% set name = "citrination-client" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df368321a3bc5c3a671a1bc24c503019015bfb9c78df6e68b154163966a87442

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - requests 
    - requests-mock 
    - six 
    - pyyaml 
    - pypif

test:
  imports:
    - citrination_client
    
about:
  home: http://github.com/CitrineInformatics/python-citrination-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Reference implementation in python for Citrination api'

  description: |
    Python client for accessing the Citrination api
  doc_url: http://citrineinformatics.github.io/python-citrination-client/
  dev_url: https://github.com/CitrineInformatics/python-citrination-client

extra:
  recipe-maintainers:
    - eddotman
    - maxhutch
    - sparadiso
    - jsomara
