travis:
  secure:
    BINSTAR_TOKEN: QeGIk8SnveQyZ3bEATCmODa8W45roJJGe0akvy8FHifWbEfaBuxZBNZVCnR3uv0l/oRN4mvYcoGK3Idy3gqMRG3SmvcMkXwfl6mCtK1d4UoamOPelEn3mTciWh82OQtmH6qL8dAxHkG+z4prH3qE8mHEUAot8qptK8oCQjkHiWoKHSH57dgQZDunV2fMDn8M69TacMmjFVOcZnFQFrj94oKS36LcUghiyQkmLWcFd9Y1IxxyHQOmVIBVe8n4XY939RKvznhz57wvALDuiWaflvUI7KG5VxgA2QZGjqtbAfwMm7mCzDJsoMgqYRN1T1CWen3ZESo6VGQrkvC83JqPXwFLfPSbbpJqQ+hpRXWtl5QJbrsaALFthBw0KqJpv5ajjSa12RwiPz1+6WJdfzFTHi4B7XJH0oTPl1PPUKx+wLWHbBgESKKjv7yIzbliMwT+fmAeUHkB4Nnq6AEkWwkHk6MO6fy7bz4DASGfRTOqCa0jRN4wsPFiui6cafmGTiEkZttLLscf+I1HkwwTIP8YWq0ar2Vlgl+hLhuZp7S+SFBt23tJbml1B0PoA+ysvLzkzJ3iM8xqRAlKVeH9qE27MDjUyVELac4loAcCF1CE5hZhUNG+rAHity9JWob+0q2+sihO2ub5kJo4+5Ixd4aBNxtCxWCLFn5y8tjqq1WF4LU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
